#!/usr/bin/env python

import itertools
import os
import site
import sys

# Get site package locations
site_packages = site.getsitepackages()
if len(site_packages) == 0:
    sys.exit('No site package locations found')

# Look for aafm script in package locations
possible_scripts = [x + '/aafm/aafm-gui.py' for x in site_packages]
scripts = [x for x in possible_scripts if os.path.isfile(x)]
if len(scripts) == 0:
    sys.exit("Did not find aafm in site package locations: "
             + ", ".join(site_packages))
if len(scripts) > 1:
    print("Located multiple aafm site packages in "
          + " and ".join(site_packages)
          + "; using the package in "
          + site_packages[0])

# Launch aafm from site-packages path and pass any arguments given
cmd = list(itertools.chain([sys.executable, scripts[0]], sys.argv[1:]))
os.system(" ".join(cmd))
